[workspace]
members = ["crates/*"]

[workspace.dependencies]
regex = "1.11.1"
serde_json = "1.0.140"
swc_core = { version = "26.0.0" }

swc_macro_condition_transform = { path = "./crates/swc_macro_condition_transform" }
swc_macro_parser = { path = "./crates/swc_macro_parser" }
